footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
obstacle_range: 3.0
raytrace_range: 3.5


inflation_radius: 0.5
cost_scaling_factor: 2.0

map_type: costmap
observation_sources: scan point_cloud_sensor

scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

pont_cloud_sensor: {data_type: sensor_msgs/PointCloud2, topic: /kinect_V2/depth/points, marking: true, clearing: true}
